### ISSUE TITLE
There is no version numbers in the requirements file

### ISSUE THREAD

**Issue by mdhasanai** [Bangla-RAG/PoRAG#7]
The requirements file currently lacks version numbers for dependencies which making it difficult to setup and run this  on my local machine. Additionally, LangChain frequently changes its version which adds to the instability. Dockerizing will be nice.

**Comment by hassanaliemon** [comment]
Hello @mdhasanai 
the version number is not intentionally put in the requirement.txt file except `bitsandbytes` which cause trouble to get `GPU`. We did not put it because it is in it's early stage and will not make problem for now.

But when it will get complicated we will specify each version of all dependencies. 

Thanks for your concern, we really appreciate your feedback, and expect to get your feedback in future as well.

**Comment by asiff00** [comment]
> The requirements file currently lacks version numbers for dependencies which making it difficult to setup and run this on my local machine. Additionally, LangChain frequently changes its version which adds to the instability. Dockerizing will be nice.


@mdhasanai Hey there, we have added version numbers to each of the main packages required for this to run. Please find it here: [requirements.txt](https://github.com/Bangla-RAG/PoRAG/blob/main/requirements.txt)
Please try again and let us know if you are still having issues with running it locally. If fails, send us screenshots/logs of any possible errors so we can focus on them.
